on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
  schedule:
    - cron: "0 5 * * 6"

name: Update Curation

jobs:
  update-curation:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: 'devel'

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Restore R package cache
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
          install.packages("roxygen2")
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .

      - name: Update curation
        run: |
          Rscript data-raw/sysdata.R
          Rscript data-raw/sampleMetadata.R

      - name: Test curation
        id: update_curation
        run: |
          library("curatedMetagenomicDataCuration")
          message(paste("\n****", Sys.time(), "Check curation ****"))
          status <- "passing"
          tryCatch(curatedMetagenomicDataCuration::checkCuration(sampleMetadata),
               warning = function(w) {
                   status <<- "failing"
                   message(paste(w, "\n"))
          })
          color = if (status == "passing") "brightgreen" else "red"
          message(paste("::set-output name=status::", status, sep=""))
          message(paste("::set-output name=color::", color, sep=""))
        shell: Rscript {0}

      - name: Get actions URL
        id: actions_url
        run: echo "::set-output name=url::${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"

      - name: Update documentation
        run: roxygen2::roxygenize()
        shell: Rscript {0}

      - name: Commit and create pull request for updated curation
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update curation
          committer: GitHub Actions <noreply@github.com>
          signoff: false
          branch: update-curation
          delete-branch: true
          title: 'Update curation'
          body: |
            Update curation.

            [![Curation Status](https://img.shields.io/badge/Curation-${{ steps.update_curation.outputs.status }}-${{ steps.update_curation.outputs.color }})](${{ steps.actions_url.outputs.url }})

            Auto-generated by [create-pull-request][1].

            [1]: https://github.com/peter-evans/create-pull-request
          labels: automated pr
          team-reviewers: |
            owners
            maintainers
          draft: false
